"""init

Revision ID: 25890a85f01f
Revises:
Create Date: 2024-09-21 19:28:00.125682

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25890a85f01f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


conn = op.get_bind()
inspector = Inspector.from_engine(conn)  # type: ignore
table_names = inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if "account" not in table_names:
        op.create_table("account", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    if "activity" not in table_names:
        op.create_table(
            "activity",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("timestamp", sa.DateTime(), nullable=False),
            sa.Column("owner_account_id", sa.Integer(), nullable=False),
            sa.Column("source_account_id", sa.Integer(), nullable=False),
            sa.Column("target_account_id", sa.Integer(), nullable=False),
            sa.Column("amount", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["owner_account_id"],
                ["account.id"],
            ),
            sa.ForeignKeyConstraint(
                ["source_account_id"],
                ["account.id"],
            ),
            sa.ForeignKeyConstraint(
                ["target_account_id"],
                ["account.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    op.drop_table("account")
    # ### end Alembic commands ###
